version: '3.3'

services:
  github:
    build:
      context: ./github
      dockerfile: Dockerfile
    container_name: "github"
    ports:
      - "8081:8080"
    restart: always

  twitter:
    build:
      context: ./twitter
      dockerfile: Dockerfile
    container_name: "twitter"
    ports:
      - "8082:8080"
    restart: always

  microservice:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    container_name: "microservice"
    depends_on:
      - github
      - twitter

    ports:
      - "8080:8080"
    restart: always 
